/*
 * Copyright (c) 2021 University of Chicago
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met: redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer;
 * redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution;
 * neither the name of the copyright holders nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Author - Andronicus
 * Initial UpStream Program to do a basic operation on data
 * Add and return value
 * AutoGenerated File!
 *
 */
#ifndef UPSTREAM_H
#define UPSTREAM_H

// TODO: Placeholder variables for changing memory mapping
// These are not currently being used
#define BASE_SPMEM_ADDR 0x0 // Base address for scratchpad memories
#define BASE_CONTROL_ADDR                                                      \
  0x0 // Base address for memory mapped control registers
#define PER_LANE_SPMEM_CAPACITY                                                \
  0x0 // Scratchpad address space capacity. Available memory may be smaller
#define PER_LANE_CONTROL_CAPACITY                                              \
  0x0 // Control signals address space capacity. Number of control registers may
      // be smaller
#define NUM_LANES 0x0 // Number of lanes per CU
#define NUM_UDS 0x0   // Number of CUs

// TODO: These values should disappear in the next version
#define MAPBASE 0x80000000   // MapBase
#define UBASE 0x200000000    // Upstream Base
#define SBASE 0x0            // ScratchPad Base (Local)
#define EBASE 0x10000        // Event Queue
#define OBASE 0x10100        // Operand Buffer Base
#define EXEC 0x10200         // Exec Addr
#define STATBASE 0x10300     // Status - Unused now
#define NUMUDS 1             // Number of Up Downs
#define NUMLANES 1           // NumLanes
#define MEMSIZE 2UL << 32    // Top Memory Size
#define MAPSIZE 1UL << 32    // Mapped Memory size
#define LMBANK_SIZE 65536    // LM Bank Size
#define LMBANK_SIZE_4B 16384 // Event Queue (Local)
#endif