/*
 * Copyright (c) 2021 University of Chicago
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met: redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer;
 * redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution;
 * neither the name of the copyright holders nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Author - Andronicus
 * Initial UpStream Program to do a basic operation on data
 * Add and return value
 * AutoGenerated File!
 *
 */
#ifndef UPSTREAM_H
#define UPSTREAM_H

// DEFAULT VALUES
#define DEF_NUM_LANES 0x1         // Number of lanes per CU
#define DEF_NUM_UDS 0x1           // Number of CUs
#define DEF_SPMEM_BANK_SIZE 65536 // Scratchpad Memory size per lane
#define DEF_WORD_SIZE 4           // Wordsize
#define DEF_MAPPED_SIZE 1UL << 32

// Base address for scratchpad memories
#define BASE_SPMEM_ADDR 0x200000000
// Base address for memory mapped control registers
#define BASE_CTRL_ADDR 0x600000000
// Scratchpad address space maximum capacity
#define SPMEM_CAPACITY_PER_LANE 1UL << 17
// Control signals address space capacity. Number of control registers may
#define CONTROL_CAPACITY_PER_LANE 1UL << 7
// Number of lanes capacity
#define NUM_LANES_CAPACITY 1UL << 7
// Number of lanes capacity
#define NUM_UDS_CAPACITY 1UL << 7

// Base address mapped memory - This is due to simulation
#define BASE_MAPPED_ADDR 0x80000000

// CONTROL SIGNALES OFFSET
#define EVENT_QUEUE_OFFSET 0x0
#define OPERAND_QUEUE_OFFSET 0x4
#define START_EXEC_OFFSET 0x8
#define LOCK_OFFSET 0xC

#endif