UpDown::SimUDRuntime_t Class Reference
Wrapper class that allows simulation of runtime calls.
#include <simupdown.h>
Public Member Functions
SimUDRuntime_t ()
Construct a new SimUDRuntime_t object.
SimUDRuntime_t (ud_machine_t machineConfig)
Construct a new SimUDRuntime_t object.
SimUDRuntime_t (std::string programFile, std::string programName, std::string simulationDir)
Construct a new SimUDRuntime_t object.
SimUDRuntime_t (ud_machine_t machineConfig, std::string programFile, std::string programName, std::string simulationDir)
Construct a new SimUDRuntime_t object.
void send_event (event_t ev)
Wrapper function for send_event.
void start_exec (uint8_t ud_id, uint8_t lane_num)
Wrapper function for start_exec.
void t2ud_memcpy (ptr_t data, uint64_t size, uint8_t ud_id, uint8_t lane_num, uint32_t offset)
Wrapper function for t2ud_memcpy.
void ud2t_memcpy (ptr_t data, uint64_t size, uint8_t ud_id, uint8_t lane_num, uint32_t offset)
Wrapper function for ud2t_memcpy.
bool test_addr (uint8_t ud_id, uint8_t lane_num, uint32_t offset, word_t expected=1)
Wrapper function for test_addr.
void test_wait_addr (uint8_t ud_id, uint8_t lane_num, uint32_t offset, word_t expected=1)
Wrapper function for test_wait_addr.
Private Member Functions
void initMemoryArrays ()
Allocate memory for the simulation of the updown.
void initPythonInterface ()
Initialize interface with python emulator.
Private Attributes
const std::string LogFileName = `Perf.log`
uint8_t * MappedMemory
uint8_t * ScratchpadMemory
uint8_t * ControlMemory
std::string programFile
std::string programName
std::string simulationDir
Upstream_PyIntf * upstream_pyintf
bool python_enabled
uint32_t ** sendmap
Additional Inherited Members
Detailed Description
Wrapper class that allows simulation of runtime calls.
This class inherits from UDRuntime_t, and it overwrites the methods such that they can be simulated using a memory region.
This class does not use polymorphism. It just oversubscribes the methods, wrapping the original implementation of the runtime
Todo
Todo This does not emulate multiple UPDs
Constructor & Destructor Documentation
SimUDRuntime_t() [1/4]
UpDown::SimUDRuntime_t::SimUDRuntime_t () [inline]
Construct a new SimUDRuntime_t object.
This constructor calls initMemoryArrays() to set the simulated memory regions. Python will be disabled. Only simulating memory interactions.
References UpDown::UDRuntime_t::calc_addrmap(), and initMemoryArrays().
SimUDRuntime_t() [2/4]
UpDown::SimUDRuntime_t::SimUDRuntime_t (ud_machine_t machineConfig) [inline]
Construct a new SimUDRuntime_t object.
This constructor calls initMemoryArrays() to set the simulated memory regions. The pointers of ud_machine_t.MappedMemBase, ud_machine_t.UDbase ud_machine_t.SPMemBase and ud_machine_t.ControlBase will be ignored and overwritten in order to simulate the runtime.
Parameters
machineConfig Machine configuration
References UpDown::UDRuntime_t::calc_addrmap(), and initMemoryArrays().
SimUDRuntime_t() [3/4]
UpDown::SimUDRuntime_t::SimUDRuntime_t (std::string programFile, std::string programName, std::string simulationDir) [inline]
Construct a new SimUDRuntime_t object.
This constructor calls initMemoryArrays() to set the simulated memory regions. The pointers of ud_machine_t.MappedMemBase, ud_machine_t.UDbase ud_machine_t.SPMemBase and ud_machine_t.ControlBase will be ignored and overwritten.
Parameters
machineConfig Machine configuration
References UpDown::UDRuntime_t::calc_addrmap(), initMemoryArrays(), and initPythonInterface().
SimUDRuntime_t() [4/4]
UpDown::SimUDRuntime_t::SimUDRuntime_t (ud_machine_t machineConfig, std::string programFile, std::string programName, std::string simulationDir) [inline]
Construct a new SimUDRuntime_t object.
This constructor calls initMemoryArrays() to set the simulated memory regions. The pointers of ud_machine_t.MappedMemBase, ud_machine_t.UDbase ud_machine_t.SPMemBase and ud_machine_t.ControlBase will be ignored and overwritten.
Parameters
machineConfig Machine configuration
References UpDown::UDRuntime_t::calc_addrmap(), initMemoryArrays(), and initPythonInterface().
Member Function Documentation
initMemoryArrays()
void UpDown::SimUDRuntime_t::initMemoryArrays () [private]
Allocate memory for the simulation of the updown.
This function allocates the MappedMemory, the Scratchpad memory and the Control Memory, used for the simulation. Then it changes the MachineConfig object to use these pointers instead of the default ones for these three memory regions.
Todo
Todo We are allocating the whole address space. We could behave more like a driver and translate it to the actual available memory. This means. It should not allocate the reserved space for expansion.
References UpDown::UDRuntime_t::MachineConfig, and UpDown::UDRuntime_t::reset_memory_manager().
Referenced by SimUDRuntime_t().
initPythonInterface()
void UpDown::SimUDRuntime_t::initPythonInterface () [private]
Initialize interface with python emulator.
This function handles initialization of the interface with python EFA emulator. The emulator is in charge of UpDown behavior.
Todo
Todo when increasing the number of lanes to multiple UpDowns, this function must be re-implemented
References UpDown::UDRuntime_t::MachineConfig, and sendmap.
Referenced by SimUDRuntime_t().
send_event()
void UpDown::SimUDRuntime_t::send_event (event_t ev)
Wrapper function for send_event.
Calls the emulator and calls the UDRuntime_t::send_event() function
References python_enabled, and UpDown::UDRuntime_t::send_event().
start_exec()
void UpDown::SimUDRuntime_t::start_exec (uint8_t ud_id, uint8_t lane_num)
Wrapper function for start_exec.
Calls the emulator and calls the UDRuntime_t::start_exec() function
References python_enabled, sendmap, UpDown::UDRuntime_t::start_exec(), and start_exec().
Referenced by start_exec().
t2ud_memcpy()
void UpDown::SimUDRuntime_t::t2ud_memcpy (ptr_t data, uint64_t size, uint8_t ud_id, uint8_t lane_num, uint32_t offset)
Wrapper function for t2ud_memcpy.
Calls the emulator and calls the UDRuntime_t::t2ud_memcpy() function
Todo
Todo The physical memory is contiguous, therefore the calculation of this offset is different to the address space in the virtual memory. Is there a way to express this? The runtime is doing some heavy lifting here that is translating things to physical memory
References UpDown::UDRuntime_t::get_lane_physical_memory(), python_enabled, and UpDown::UDRuntime_t::t2ud_memcpy().
test_addr()
bool UpDown::SimUDRuntime_t::test_addr (uint8_t ud_id, uint8_t lane_num, uint32_t offset, word_t expected = 1)
Wrapper function for test_addr.
Calls the emulator and calls the UDRuntime_t::test_addr() function
Todo
Todo The physical memory is contiguous, therefore the calculation of this offset is different to the address space in the virtual memory. Is there a way to express this? The runtime is doing some heavy lifting here that is translating things to physical memory
References UpDown::UDRuntime_t::BaseAddrs, UpDown::UDRuntime_t::get_lane_aligned_offset(), UpDown::UDRuntime_t::get_lane_physical_memory(), python_enabled, and UpDown::UDRuntime_t::test_addr().
Referenced by test_wait_addr().
test_wait_addr()
void UpDown::SimUDRuntime_t::test_wait_addr (uint8_t ud_id, uint8_t lane_num, uint32_t offset, word_t expected = 1)
Wrapper function for test_wait_addr.
Calls the emulator and calls the UDRuntime_t::test_wait_addr() function
Todo
Todo The physical memory is contiguous, therefore the calculation of this offset is different to the address space in the virtual memory. Is there a way to express this? The runtime is doing some heavy lifting here that is translating things to physical memory
References test_addr(), and UpDown::UDRuntime_t::test_wait_addr().
ud2t_memcpy()
void UpDown::SimUDRuntime_t::ud2t_memcpy (ptr_t data, uint64_t size, uint8_t ud_id, uint8_t lane_num, uint32_t offset)
Wrapper function for ud2t_memcpy.
Calls the emulator and calls the UDRuntime_t::ud2t_memcpy() function
This function copies from the emulator directly into the scratchpad memory and then calls the real runtime function. This allows to keep the logic of the real runtime even though we are simulating the hardware
Todo
Todo The physical memory is contiguous, therefore the calculation of this offset is different to the address space in the virtual memory. Is there a way to express this? The runtime is doing some heavy lifting here that is translating things to physical memory
References UpDown::UDRuntime_t::BaseAddrs, UpDown::UDRuntime_t::get_lane_aligned_offset(), UpDown::UDRuntime_t::get_lane_physical_memory(), python_enabled, and UpDown::UDRuntime_t::ud2t_memcpy().
Member Data Documentation
python_enabled
bool UpDown::SimUDRuntime_t::python_enabled [private]
When python is not enabled, we bypass all the calls to the python interface. This restricts simulation to only memory operations
Referenced by send_event(), start_exec(), t2ud_memcpy(), test_addr(), and ud2t_memcpy().
sendmap
uint32_t** UpDown::SimUDRuntime_t::sendmap [private]
Contains a mapped memory to the file system that is used to communicate with the emulator.
Referenced by initPythonInterface(), and start_exec().
The documentation for this class was generated from the following files:
/Users/josemonsalvediaz/Documents/Project38/llvm/updown/simruntime/include/simupdown.h
/Users/josemonsalvediaz/Documents/Project38/llvm/updown/simruntime/src/simupdown.cpp