UpDown::UDRuntime_t Class Reference
Class containing the UpDown Runtime.
#include <updown.h>
Classes
struct base_addr_t
Struct containing all the base addresses.
class ud_mapped_memory_t
This is a class to manage the mapped memory.
Public Member Functions
UDRuntime_t (ud_machine_t machineConfig)
void send_event (event_t ev)
Sends an event to the UpDown.
void start_exec (uint8_t ud_id, uint8_t lane_num)
Signal lane to start execution.
void * mm_malloc (uint64_t size)
Memory allocator for the mapped memory.
void mm_free (void *ptr)
Free an already existing memory allocation.
void t2mm_memcpy (uint64_t offset, ptr_t src, uint64_t size=1)
Copy to mapped memory from top.
void mm2t_memcpy (uint64_t offset, ptr_t dst, uint64_t size=1)
Copy from mapped memory to top.
void t2ud_memcpy (ptr_t data, uint64_t size, uint8_t ud_id, uint8_t lane_num, uint32_t offset)
Copy data from the top to the scratchpad memory.
void ud2t_memcpy (ptr_t data, uint64_t size, uint8_t ud_id, uint8_t lane_num, uint32_t offset)
Copy data from the scratchpad memory to the top.
bool test_addr (uint8_t ud_id, uint8_t lane_num, uint32_t offset, word_t expected=1)
Test a memory location in the updwon bank for the expected value.
void test_wait_addr (uint8_t ud_id, uint8_t lane_num, uint32_t offset, word_t expected=1)
Test a memory location in the updown bank for the expected value. Wait until it is the expected value.
uint64_t get_lane_physical_memory (uint8_t ud_id, uint8_t lane_num, uint32_t offset=0)
Get offset in local memory.
void dumpBaseAddrs ()
Helper function to dump current base addresses.
void dumpMachineConfig ()
Helper function to dump current Machine Config.
Protected Member Functions
void calc_addrmap ()
Initializes the base addresses for queues and states.
uint64_t get_lane_aligned_offset (uint8_t ud_id, uint8_t lane_num, uint32_t offset=0)
Get the aligned offset object.
void reset_memory_manager ()
Reset the Memory Manager when machine configuration is changed;.
Protected Attributes
base_addr_t BaseAddrs
container for all base addresses
ud_machine_t MachineConfig
Contains configuration parameters of the machine abstraction.
ud_mapped_memory_t * MappedMemoryManager
Detailed Description
Class containing the UpDown Runtime.
This class is the entry point of the UpDown runtime, it manages all the necessary state, keeps track of pointers and memory allocation and coordinates execution of code.
Member Function Documentation
calc_addrmap()
void UpDown::UDRuntime_t::calc_addrmap () [protected]
Initializes the base addresses for queues and states.
This function initializes BaseAddrs according to the configuration file for their use in the rest of the runtime
References BaseAddrs, and MachineConfig.
Referenced by UpDown::SimUDRuntime_t::SimUDRuntime_t().
dumpBaseAddrs()
void UpDown::UDRuntime_t::dumpBaseAddrs () [inline]
Helper function to dump current base addresses.
This function has no effect on runtime, but it is useful for debugging
References BaseAddrs.
dumpMachineConfig()
void UpDown::UDRuntime_t::dumpMachineConfig () [inline]
Helper function to dump current Machine Config.
This function has no effect on runtime, but it is useful for debugging
References MachineConfig.
get_lane_aligned_offset()
uint64_t UpDown::UDRuntime_t::get_lane_aligned_offset (uint8_t ud_id, uint8_t lane_num, uint32_t offset = 0) [inline], [protected]
Get the aligned offset object.
Parameters
ud_id UpDown ID
lane_num Lane ID
offset Offset in bytes
Returns
uint64_t
References MachineConfig.
Referenced by t2ud_memcpy(), test_addr(), UpDown::SimUDRuntime_t::test_addr(), test_wait_addr(), ud2t_memcpy(), and UpDown::SimUDRuntime_t::ud2t_memcpy().
get_lane_physical_memory()
uint64_t UpDown::UDRuntime_t::get_lane_physical_memory (uint8_t ud_id, uint8_t lane_num, uint32_t offset = 0)
Get offset in local memory.
This is a temporary solution to the absence of an appropriate virtual memory mapping. This functions assumes that physical memory side is contiguous and it does not have space for expansion. This is, instead of using the Scratchpad Capacity that is explained in UDRuntime_t::base_addr_t, it uses the actual size of the Scratchpad Memory.
Currently, this function is used to allow pointers to be passed from top to updown.
Scratchpad physical memory for 1 UD
*        MEMORY                     SIZE
*   |--------------|  <-- Scratchpad Base Address
*   |              |
*   |    Lane 0    |
*   |              |
*   |--------------|  <-- SPmem BankSize
*   |              |
*   |    Lane 1    |
*   |              |
*   |--------------|  <-- 2 * SPmem BankSize
*   |      ...     |
*   |--------------|  <-- (NumLanes-1) * SPmem BankSize
*   |              |
*   |    Lane N    |
*   |              |
*   |--------------|  <-- (NumLanes) * SPmem BankSize
* 
Parameters
ud_id UpDown ID
lane_num Lane ID
offset Offset in bytes
Returns
uint64_t
References MachineConfig.
Referenced by UpDown::SimUDRuntime_t::t2ud_memcpy(), UpDown::SimUDRuntime_t::test_addr(), and UpDown::SimUDRuntime_t::ud2t_memcpy().
mm2t_memcpy()
void UpDown::UDRuntime_t::mm2t_memcpy (uint64_t offset, ptr_t dst, uint64_t size = 1)
Copy from mapped memory to top.
Mapped memory is a region in DRAM that can be accessed from updown. This is necessary due to the lack of support for virtual memories in the UpDown. The UpDown will be able to use pointers directly into this region without need for address translation.
Parameters
offset Destination offset within the memory mapped region
dst Source pointer
size size in words
References BaseAddrs.
mm_free()
void UpDown::UDRuntime_t::mm_free (void * ptr)
Free an already existing memory allocation.
Mapped memory is a region in DRAM that can be accessed from updown. This is necessary due to the lack of support for virtual memories in the UpDown. The UpDown will be able to use pointers directly into this region without need for address translation.
Todo
Todo : This should be thread safe?
Parameters
ptr pointer to deallocate
References UpDown::UDRuntime_t::ud_mapped_memory_t::remove_region().
mm_malloc()
void * UpDown::UDRuntime_t::mm_malloc (uint64_t size)
Memory allocator for the mapped memory.
Mapped memory is a region in DRAM that can be accessed from updown. This is necessary due to the lack of support for virtual memories in the UpDown. The UpDown will be able to use pointers directly into this region without need for address translation.
Todo
Todo : This should be thread safe?
Parameters
size size in bytes
Returns
void * Pointer to the location.
References UpDown::UDRuntime_t::ud_mapped_memory_t::get_region().
reset_memory_manager()
void UpDown::UDRuntime_t::reset_memory_manager () [inline], [protected]
Reset the Memory Manager when machine configuration is changed;.
Referenced by UpDown::SimUDRuntime_t::initMemoryArrays().
send_event()
void UpDown::UDRuntime_t::send_event (event_t ev)
Sends an event to the UpDown.
Sends a new event to the updown event queues. Information about the destination of the event is defined in the ev parameter, including destination UD_ID, lane_id, thread_id. The event_t also contains the operands
Parameters
ev the event to be sent
References BaseAddrs, and MachineConfig.
Referenced by UpDown::SimUDRuntime_t::send_event().
start_exec()
void UpDown::UDRuntime_t::start_exec (uint8_t ud_id, uint8_t lane_num)
Signal lane to start execution.
Parameters
ud_id UpDown ID
lane_num lane to signal
References BaseAddrs, and MachineConfig.
Referenced by UpDown::SimUDRuntime_t::start_exec().
t2mm_memcpy()
void UpDown::UDRuntime_t::t2mm_memcpy (uint64_t offset, ptr_t src, uint64_t size = 1)
Copy to mapped memory from top.
Mapped memory is a region in DRAM that can be accessed from updown. This is necessary due to the lack of support for virtual memories in the UpDown. The UpDown will be able to use pointers directly into this region without need for address translation.
Parameters
offset Destination offset within the memory mapped region
src Source pointer
size size in words
References BaseAddrs.
t2ud_memcpy()
void UpDown::UDRuntime_t::t2ud_memcpy (ptr_t data, uint64_t size, uint8_t ud_id, uint8_t lane_num, uint32_t offset)
Copy data from the top to the scratchpad memory.
This function sends data to the bank associated with the lane_num The address is calculated based on the offset.
Parameters
data pointer to the top data to be copied over to the lane
size The number of words to be copied to the scratchpad memory
ud_id UpDown number
lane_num lane bank
offset offset within bank in bytes
References BaseAddrs, and get_lane_aligned_offset().
Referenced by UpDown::SimUDRuntime_t::t2ud_memcpy().
test_addr()
bool UpDown::UDRuntime_t::test_addr (uint8_t ud_id, uint8_t lane_num, uint32_t offset, word_t expected = 1)
Test a memory location in the updwon bank for the expected value.
Reads the updown scratchpad memory bank, and check if the value is equal to the expected value. Returns true if the values are equal
Parameters
ud_id UpDown number
lane_num LaneID to check
offset offset within the memory bank in bytes
expected value that is expected in the memory bank
Returns
word_t
References BaseAddrs, and get_lane_aligned_offset().
Referenced by UpDown::SimUDRuntime_t::test_addr().
test_wait_addr()
void UpDown::UDRuntime_t::test_wait_addr (uint8_t ud_id, uint8_t lane_num, uint32_t offset, word_t expected = 1)
Test a memory location in the updown bank for the expected value. Wait until it is the expected value.
Spinwaiting on a location of the updown scratchpad memory bank until the value read is the expected value. Uses lane_test_memory.
Parameters
lane_num LaneID to check
offset offset within the memory bank in bytes
expected value that is expected in the memory bank
References BaseAddrs, and get_lane_aligned_offset().
Referenced by UpDown::SimUDRuntime_t::test_wait_addr().
ud2t_memcpy()
void UpDown::UDRuntime_t::ud2t_memcpy (ptr_t data, uint64_t size, uint8_t ud_id, uint8_t lane_num, uint32_t offset)
Copy data from the scratchpad memory to the top.
Parameters
data pointer to the top data to be contain values from the scratchpad memory
size The number of words to be copied from the scratchpad memory
ud_id UpDown number
lane_num lane bank
offset offset within bank in bytes
References BaseAddrs, and get_lane_aligned_offset().
Referenced by UpDown::SimUDRuntime_t::ud2t_memcpy().
Member Data Documentation
BaseAddrs
base_addr_t UpDown::UDRuntime_t::BaseAddrs [protected]
container for all base addresses
Referenced by calc_addrmap(), dumpBaseAddrs(), mm2t_memcpy(), send_event(), start_exec(), t2mm_memcpy(), t2ud_memcpy(), test_addr(), UpDown::SimUDRuntime_t::test_addr(), test_wait_addr(), ud2t_memcpy(), and UpDown::SimUDRuntime_t::ud2t_memcpy().
MachineConfig
ud_machine_t UpDown::UDRuntime_t::MachineConfig [protected]
Contains configuration parameters of the machine abstraction.
Referenced by calc_addrmap(), dumpMachineConfig(), get_lane_aligned_offset(), get_lane_physical_memory(), UpDown::SimUDRuntime_t::initMemoryArrays(), UpDown::SimUDRuntime_t::initPythonInterface(), send_event(), and start_exec().
The documentation for this class was generated from the following files:
/Users/josemonsalvediaz/Documents/Project38/llvm/updown/runtime/include/updown.h
/Users/josemonsalvediaz/Documents/Project38/llvm/updown/runtime/src/updown.cpp