UpDown::operands_t Class Reference
Class that holds information about the operands.
#include <updown.h>
Public Member Functions
operands_t ()
Construct a new empty operands_t object.
operands_t (const operands_t &o)
Copy Constructor.
operands_t (operands_t &&o)
Copy Constructor.
operands_t (uint8_t num, ptr_t oper, word_t cont=0)
Construct a new operands_t opbejct, setting the operands.
operands_t (uint8_t num, word_t cont=0)
Construct a new operands_t opbejct,.
ptr_t get_Data ()
Get the pointer to Data.
void set_operand (uint32_t op, word_t val)
Set an operand.
void set_operands (uint32_t op_begin, uint32_t op_end, void *val)
Set multiple operands at once.
void set_cont (word_t cont)
Set the Continuation.
uint8_t get_NumOperands ()
Get the NumOperands.
Private Attributes
uint8_t NumOperands
ptr_t Data
Detailed Description
Class that holds information about the operands.
Contains a pointer to data and the number of operands. data is an array of ptr_t, representing each word in the operand buffer when copied.
Constructor & Destructor Documentation
operands_t() [1/5]
UpDown::operands_t::operands_t () [inline]
Construct a new empty operands_t object.
Set the Data pointer to null and NumOperands to 0
operands_t() [2/5]
UpDown::operands_t::operands_t (const operands_t & o) [inline]
Copy Constructor.
Parameters
o other object
operands_t() [3/5]
UpDown::operands_t::operands_t (operands_t && o) [inline]
Copy Constructor.
Parameters
o other object
operands_t() [4/5]
UpDown::operands_t::operands_t (uint8_t num, ptr_t oper, word_t cont = 0) [inline]
Construct a new operands_t opbejct, setting the operands.
Parameters
num Number of operaqnds
oper Operand value
cont Continuation event
Todo
Todo This should avoid using memcpy
References get_NumOperands().
operands_t() [5/5]
UpDown::operands_t::operands_t (uint8_t num, word_t cont = 0) [inline]
Construct a new operands_t opbejct,.
Parameters
num Number of operaqnds
cont Continuation event
Todo
Todo This should avoid using memcpy
Member Function Documentation
get_Data()
ptr_t UpDown::operands_t::get_Data () [inline]
Get the pointer to Data.
Returns
ptr_t pointer to data
get_NumOperands()
uint8_t UpDown::operands_t::get_NumOperands () [inline]
Get the NumOperands.
Returns
uint8_t number of operands
Referenced by UpDown::event_t::event_t(), operands_t(), and UpDown::event_t::set_event().
set_cont()
void UpDown::operands_t::set_cont (word_t cont) [inline]
Set the Continuation.
Parameters
cont
set_operand()
void UpDown::operands_t::set_operand (uint32_t op, word_t val) [inline]
Set an operand.
Parameters
op operand number
val value for the operand
set_operands()
void UpDown::operands_t::set_operands (uint32_t op_begin, uint32_t op_end, void * val) [inline]
Set multiple operands at once.
Example:
// Mapping a struct to different operands
// Assume no padding
struct A {
 word_t v1; // 4 bytes
 word_t v2; // 4 bytes
 int * ptr; // 8 bytes
};
// Assuming word_t is 4 bytes,
// size of A should be 16 bytes, using
// 4 elements in the operand buffer
int anInt;
A myStr = {1, 2, &anInt};
rt.set_operands(0,4, &myStr);
// the struct will be copied bit a bit, each
// operand in a different location.
Parameters
op_begin Start operand inclusive
op_end End operand inclusive
val pointer to the value to be copied
The documentation for this class was generated from the following file:
/Users/josemonsalvediaz/Documents/Project38/llvm/updown/runtime/include/updown.h